### ISSUE TITLE
[STF] Ability to filter items in JAPacks

### ISSUE THREAD

**Issue by hhuuggss** [ChroniclerCherry/stardew-valley-mods#16]
It'd be handy to be able to only add JAPack items of a certain category, or to only add items by name if they're in a specific pack.

Right now it's possible to add specific JA items by name, but this sometimes has unintended results ("Lime" returning limestone instead of limes from More Trees)

**Comment by ChroniclerCherry** [comment]
Right now you can already only add JA packs of a particular ItemType at a time

But oh boy that sounds like a bug. I can squash that next time I sit down!

It should be only grabbing names by a full match, but I'm currently searching the beginning of the object info string. Did not think this far ahead XD

**Comment by ChroniclerCherry** [comment]
Fixed in commit a46ec07a958e9090288bb77a4bd2499ece826b43
