### ISSUE TITLE
[STF] Suggestion for price of items

### ISSUE THREAD

**Issue by Lumisteria** [ChroniclerCherry/stardew-valley-mods#22]
- Being able to have a range for the price, so price can be randomized between the two values. It would allow shops similar to the cart lady's one, when it will be possible to find some nice offers rarely.
- Being able to use modifiers of price like sellprice*1.5 or sellprice*2. This would allow to quickly set up a shop without needing to put individual prices for each items when still having them sold for higher of the sell price.

With both option, someone can imagine a shop selling items for 1.5 to 4 the sellprice, for example, for a shop selling good at random prices, without having to list the range of each items.

**Comment by ChroniclerCherry** [comment]
Added in commit 946ade05cd048c63a42111d2666a6cfd9465821a

You can now conditionally set price modifiers. Not quite a randomizer, I might add that in in the future

And added `DefaultSellPriceMultipler` which will set the price of any item not given an explicit price to their `sell price x the multipler`
