### ISSUE TITLE
[STF] Allow add item stocks to top of the list for Vanilla Shops

### ISSUE THREAD

**Issue by smujaddid** [ChroniclerCherry/stardew-valley-mods#28]
As the title above, if possible, allow new custom stocks to be added to Vanilla Shop before vanilla stocks.

Maybe something like:

```
if (ShopManager.VanillaShops["PierreShop"].ShouldPrepend)
    __result = customStock.Concat(__result).ToDictionary(x => x.Key, x => x.Value);
else
    __result = __result.Concat(customStock).ToDictionary(x => x.Key, x => x.Value);
```
Thanks.

**Comment by ChroniclerCherry** [comment]
Yeah sure, that'll be easy enough. I don't know if I'll have time this week since I'm working, but I'll definitely add it by next weekend

**Comment by ChroniclerCherry** [comment]
Added as a `AddStockAboveVanilla` field in commit f2d6a166450f80ee20bf77ac248eea9371dbf831. Will be in next week's release

**Comment by smujaddid** [comment]
Thank you!
