### ISSUE TITLE
[STF] Removing only parts of a pack (Enhancement)

### ISSUE THREAD

**Issue by Traehgniw** [ChroniclerCherry/stardew-valley-mods#31]
It would be nice to be able to remove JA items or recipes by name or to be able to define exceptions to a pack remove by name, instead of it being entirely all-or-nothing; this would allow for eg Gus selling an expanded stock of prepared food and drink, but no modded recipes or ingredients.

**Comment by ChroniclerCherry** [comment]
Hello, thanks for the suggestion! I've already separated removing items from vanilla shops by items vs recipes, but that's a good idea to let people narrow it down even more by naming specific items! It should be included in the next release
