### ISSUE TITLE
[STF] Would it be possible to add random date selection to When conditions?

### ISSUE THREAD

**Issue by LenneDalben** [ChroniclerCherry/stardew-valley-mods#33]
What I was attempting to do was, as part of the When condition, have a random selection between 3 date ranges: days 22-28, days 26-28, and day 28 only. The point being, in one month, the stock is sold on day 28 only, in another month it could be sold for 3 days (26-28), and in another month it could sold for 7 days (22-28). The options are randomly selected each month, which I plan to indicate by season.

**Comment by ChroniclerCherry** [comment]
To allow this to be done but in a more generally useful way, I can offer a seeded random number you can check against that stays the same over a specified period. The syntax would look something like this:

`SeededRandom <s:timePeriod> <i:offset> <f:lower range of check> <f:higher range of check>`

Where the available time periods would be `Day`,`Week`,`Season`,`Year`,`Game` ( with Game being that it returns the same number always for that play file )

Offset being just another number to be added to the random seed, allowing several separate seeded randoms. Conditions using the same offset will always return the same random number

Example:
`SeededRandom Season 1 0.5 0.8`

Would return true if the random number for that each is between 0.5 and 0.8. The random number for each Season will always be the same for that play file, allowing you to persist that randomly across multiple days

Example for your use case:
```js
"When":[
"u 22 23 24 25 26 27 28/SeededRandom 1 Season 0 0.25",
"u 26 27 28/SeededRandom 1 Season 0.25 0.50",
"u 28/SeededRandom 1 Season 0.50 0.75"]
```
