### ISSUE TITLE
[STF] A HasRecipe check and a check for the last farmhouse upgrade

### ISSUE THREAD

**Issue by LenneDalben** [ChroniclerCherry/stardew-valley-mods#34]
Hi ChroniclerCherry,
I know we discussed this in the Stardew Valley Discord in #making-mods, but I thought you might appreciate being able to cross it off a proverbial list :)
For STF, could you add to the When checks a HasRecipe check, and a check for the last farmhouse upgrade? These aren't currently checks in the vanilla game. For my purposes, either one of these would help me in a mod I'm making to ensure that an NPC doesn't sell a machine before the player has learned that recipe (the last farmhouse upgrade check was for the casks).

**Comment by ChroniclerCherry** [comment]
Thanks! I've pinned [this issue](https://github.com/ChroniclerCherry/stardew-valley-mods/issues/8) as the place to put custom condition requests, so I can keep it all in one place
