### ISSUE TITLE
[CCS] Can cooking-recipe crafting stations be made to pull ingredients from fridges?

### ISSUE THREAD

**Issue by Traehgniw** [ChroniclerCherry/stardew-valley-mods#35]
Not necessarily like, fancy modded fridges - just the vanilla fridge and minifridges, like the vanilla cooking station.

I installed a mod for decluttering the kitchen menu but it doesn't care about what's in the fridge, only what's in my inventory.

**Comment by ChroniclerCherry** [comment]
The next major feature plan for CCS is workbench-like behaviour. The main hurdle for me is learning how to handle the multiplayer code for it, but once that is done it should be simple to implement and make customizable.

The current main goals is this:
1.  If in the farmhouse, pull ingredients from fridge and minifridges
2. Pull from all chests from a configurable radius ( 0 would mean the current behaviour of only using the player inventory, 1 would mean workbench behaviour of only adjacent chests, 2 would be everything within 2 tiles, etc )

After that for compatibility, the following will be considered:
1. If Better Workbenches are installed, enable better workbench behaviour ( which is all chests that touch another chest that ultimately is adjacent to the crafting station will work )
2. If remote fridge storage is enabled, allow to pull from all marked fridge chests ( may be a problem as remote fridge storage does not handle multiplayer code at all. Compatibility might not be possible if I want to maintain proper MP sync )
