### ISSUE TITLE
Not Installing the Mod when loading the game

### ISSUE THREAD

**Issue by kate-anderson05** [ChroniclerCherry/stardew-valley-mods#86]
When loading the game and SMAPI loads up all the mods it tells me that some mods couldn't be added to the game because "Shop Tile Framework 1.0.9 because it requires mods that aren't installed (Cherry.ExpandedPreconditionsUtility)." 
I went to Nexus and downloaded the mod and added it to the proper folder and made sure it was the more recent one, do you think you could explain to me what is wrong, or try and help me fix it.

**Comment by cicuss013** [comment]
The problem is that this file is not compatible anymore. We need an update. I hope Cherry update it for Us.

**Comment by Pathoschild** [comment]
The upcoming Shop Tile Framework 1.0.10 updates to Stardew Valley 1.6 and SMAPI 4.0.0. Thanks for reporting it!
