### ISSUE TITLE
[HayBalesSilo] [Suggestion] Int to Double

### ISSUE THREAD

**Issue by VasVadum** [ChroniclerCherry/stardew-valley-mods#88]
https://github.com/ChroniclerCherry/stardew-valley-mods/blob/master/HayBalesSilo/Mod.cs#L172
`public int HayBaleEquivalentToHowManySilos { get; set; } = 1;`
to
`public double HayBaleEquivalentToHowManySilos { get; set; } = 1.0;`
(As suggested by ChatGPT to change variable type for decimal usage)

The reason for this suggestion, is that I wanted to reduce the storage to 24, 1/10th the silo storage size, for balance and realism. To show the hay bales next to the hay bales silo mod, here's a screenshot. You can see why I would want the small hay bail to be 1/10th the storage capacity as the mod that turns the entire silo into a stack of them.
![image](https://github.com/ChroniclerCherry/stardew-valley-mods/assets/1490797/3ee598ff-a94a-482c-8ce3-227dac5158e2)

**Comment by Pathoschild** [comment]
Done in the upcoming Hay Bales as Silos 1.1.0, which replaces the `HayBaleEquivalentToHowManySilos` option with a more flexible `HayPerBale`. For example, you can now do this:
```json
"HayPerBale": 24
```
Thanks for the suggestion!
